// Lista com 40 palavras em português
const WORDS = [
  'REACT','NEXT','JAVASCRIPT','COMPONENTE','ESTADO','PROPRIEDADE','HOOKS','FUNCTION','VARIAVEL','OBJETO',
  'ARRAY','STRING','TIPAGEM','ASINCRONO','PROMISSE','DOMINIO','FORCA','SENHA','FRUTA','BANANA',
  'ABACATE','TECLADO','MONITOR','CELULAR','NOTEBOOK','SISTEMA','BACKEND','FRONTEND','DESIGN','INTERFACE',
  'SENHOR','MUNDO','BRASIL','AMIZADE','ESCOLA','UNIVERSIDADE','PROJETO','ALGORITMO','LOOP','CONDICAO'
]

export function randomWord() {
  const i = Math.floor(Math.random() * WORDS.length)
  return WORDS[i].toUpperCase()
}

export default WORDS